site_name: Yale Center for Research Computing

theme:
    name: material
    custom_dir: 'theme'
    primary: '#0e4c92'
    accent: '#0e4c92'
    logo:
        icon: 'library_books'
    favicon: '/assets/images/favicon.ico'

    feature:
        tabs: true

extra_css:
    - 'stylesheets/extra.css'

markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.details
    - pymdownx.keys
    - attr_list



nav:
    - Support:
        - index.md
        - Clusters at Yale:
            - clusters-at-yale/index.md
            - Request an Account: https://research.computing.yale.edu/account-request
            - clusters-at-yale/troubleshoot.md
            - Accessing the Clusters:
                - clusters-at-yale/access/index.md
                - clusters-at-yale/access/vpn.md
                - clusters-at-yale/access/x11.md
                - clusters-at-yale/access/vnc.md
            - Applications & Software:
                - clusters-at-yale/applications/index.md
                - Loading Software with Modules: clusters-at-yale/applications/modules.md
            - Job Scheduling:
                - clusters-at-yale/job-scheduling/index.md
                - Running Jobs with Slurm: clusters-at-yale/job-scheduling/slurm.md
            - Data & Storage:
                - clusters-at-yale/data/index.md
                - Transferring Data: clusters-at-yale/data/transfer.md
            - Clusters:
                - clusters-at-yale/clusters/index.md
                - Grace: clusters-at-yale/clusters/grace.md
                - Farnam: clusters-at-yale/clusters/farnam.md
                - Ruddle: clusters-at-yale/clusters/ruddle.md
                - Milgram: clusters-at-yale/clusters/milgram.md